export const COMPANY_CATALOG = [
  { name: 'Amazon', icon: 'amazon', desc: '亚马逊是一家覆盖电商、云计算与数字内容的科技公司。' },
  { name: 'AMD', icon: 'amd', desc: 'AMD 是一家设计 CPU、GPU 等高性能芯片的半导体公司。' },
  { name: 'Automattic', icon: 'automattic', desc: 'Automattic 是运营 WordPress.com 等产品的互联网公司。' },
  { name: 'Block', icon: 'block', desc: 'Block 是一家提供支付、收款与金融工具的金融科技公司。' },
  { name: 'Box', icon: 'box', desc: 'Box 是一家提供企业云内容管理与协作服务的公司。' },
  { name: 'Cisco', icon: 'cisco', desc: '思科是一家提供网络设备、通信与安全方案的科技公司。' },
  { name: 'Cloudflare', icon: 'cloudflare', desc: 'Cloudflare 是一家提供 CDN、网络安全与边缘计算服务的公司。' },
  { name: 'Comcast', icon: 'comcast', desc: 'Comcast 是一家经营宽带、通信与媒体业务的公司。' },
  { name: 'CrowdStrike', icon: 'crowdstrike', desc: 'CrowdStrike 是一家提供云端终端防护的网络安全公司。' },
  { name: 'Databricks', icon: 'databricks', desc: 'Databricks 是一家提供数据工程与分析平台的公司。' },
  { name: 'Dell', icon: 'dell', desc: '戴尔是一家提供个人电脑、服务器与企业 IT 方案的公司。' },
  { name: 'DigitalOcean', icon: 'digitalocean', desc: 'DigitalOcean 是一家面向开发者提供云计算服务的公司。' },
  { name: 'DoorDash', icon: 'doordash', desc: 'DoorDash 是一家连接餐饮商家、骑手与用户的配送平台。' },
  { name: 'GitHub', icon: 'github', desc: 'GitHub 是一家提供代码托管与开发协作平台的公司。' },
  { name: 'GitLab', icon: 'gitlab', desc: 'GitLab 是一家提供一体化 DevSecOps 平台的公司。' },
  { name: 'Google', icon: 'google', desc: 'Google 是一家经营搜索、广告、云计算与互联网服务的公司。' },
  { name: 'IBM', icon: 'ibm', desc: 'IBM 是一家提供企业软件、咨询与计算基础设施的科技公司。' },
  { name: 'Intel', icon: 'intel', desc: '英特尔是一家设计与制造处理器等芯片产品的半导体公司。' },
  { name: 'Meta', icon: 'meta', desc: 'Meta 是一家运营 Facebook、Instagram 等社交平台的公司。' },
  { name: 'Microsoft', icon: 'microsoft', desc: '微软是一家提供软件、云计算、操作系统与游戏平台的科技公司。' },
  { name: 'NVIDIA', icon: 'nvidia', desc: '英伟达是一家设计 GPU 与加速计算平台的半导体公司。' },
  { name: 'Notion', icon: 'notion', desc: 'Notion 是一家提供文档、知识库与协作工作区的公司。' },
  { name: 'Palantir', icon: 'palantir', desc: 'Palantir 是一家提供大型数据整合与分析平台的公司。' },
  { name: 'Postman', icon: 'postman', desc: 'Postman 是一家提供 API 设计、测试与协作平台的公司。' },
  { name: 'Red Hat', icon: 'redhat', desc: '红帽是一家提供 Linux 与企业开源软件方案的公司。' },
  { name: 'Replit', icon: 'replit', desc: 'Replit 是一家提供浏览器编程与云端开发环境的公司。' },
  { name: 'SAP', icon: 'sap', desc: 'SAP 是一家提供企业资源规划与商业软件的公司。' },
  { name: 'ServiceNow', icon: 'servicenow', desc: 'ServiceNow 是一家提供企业数字工作流平台的公司。' },
  { name: 'Siemens', icon: 'siemens', desc: '西门子是一家覆盖工业自动化、能源与数字化的科技公司。' },
  { name: 'SpaceX', icon: 'spacex', desc: 'SpaceX 是一家研发火箭、卫星与太空运输系统的公司。' },
  { name: 'Stack Overflow', icon: 'stackoverflow', desc: 'Stack Overflow 是一个面向程序员的问答与知识社区。' },
  { name: 'Uber', icon: 'uber', desc: 'Uber 是一家提供网约车、配送与本地出行服务的平台公司。' },
  { name: 'Vercel', icon: 'vercel', desc: 'Vercel 是一家提供前端部署与云开发平台的公司。' },
  { name: 'Zoom', icon: 'zoom', desc: 'Zoom 是一家提供视频会议与在线协作服务的公司。' },
  { name: 'Mozilla', icon: 'mozilla', desc: 'Mozilla 是推动开放网络并开发 Firefox 的互联网组织。' },
  { name: 'Dropbox', icon: 'dropbox', desc: 'Dropbox 是一家提供云存储、文件同步与协作服务的公司。' },
  { name: 'Shopify', icon: 'shopify', desc: 'Shopify 是一家提供电商建站、支付与商家工具的公司。' },
  { name: 'Salesforce', icon: 'salesforce', desc: 'Salesforce 是一家提供客户关系管理云软件的公司。' },
  { name: 'Stripe', icon: 'stripe', desc: 'Stripe 是一家为互联网商家提供在线支付基础设施的公司。' },
  { name: 'Airbnb', icon: 'airbnb', desc: 'Airbnb 是一家连接旅行者与住宿提供者的互联网平台。' },
  { name: 'Spotify', icon: 'spotify', desc: 'Spotify 是一家提供音乐与播客流媒体服务的公司。' },
  { name: 'Netflix', icon: 'netflix', desc: 'Netflix 是一家提供影视内容制作与流媒体播放的公司。' },
  { name: 'Adobe', icon: 'adobe', desc: 'Adobe 是一家提供创意设计、文档与数字体验软件的公司。' },
  { name: 'Oracle', icon: 'oracle', desc: '甲骨文是一家提供数据库、企业软件与云服务的公司。' },
  { name: 'Atlassian', icon: 'atlassian', desc: 'Atlassian 是一家提供项目管理与开发协作工具的公司。' },
  { name: 'PayPal', icon: 'paypal', desc: 'PayPal 是一家提供网络支付与数字钱包服务的公司。' },
  { name: 'Pinterest', icon: 'pinterest', desc: 'Pinterest 是一家提供图片收藏与视觉发现服务的平台公司。' },
  { name: 'Snap', icon: 'snapchat', desc: 'Snap 是一家经营 Snapchat 与相机社交产品的公司。' },
  { name: 'Reddit', icon: 'reddit', desc: 'Reddit 是一家运营主题社区与讨论平台的互联网公司。' },
  { name: 'Roblox', icon: 'roblox', desc: 'Roblox 是一家提供用户创作游戏与虚拟社区的平台公司。' },
  { name: 'Unity', icon: 'unity', desc: 'Unity 是一家提供实时 3D 内容与游戏开发引擎的公司。' },
  { name: 'Samsung', icon: 'samsung', desc: '三星是一家覆盖消费电子、显示器与半导体的科技公司。' },
  { name: 'Sony', icon: 'sony', desc: '索尼是一家经营电子产品、游戏、音乐与影视业务的公司。' },
  { name: 'Alibaba', icon: 'alibabadotcom', desc: '阿里巴巴是一家覆盖电商、云计算与数字服务的互联网公司。' },
  { name: 'Tencent', icon: 'tencentqq', desc: '腾讯是一家经营社交、游戏、内容与数字服务的互联网公司。' },
]

const LEGACY_ICON_URLS = {
  amazon: 'https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/amazon.svg',
  ibm: 'https://cdn.jsdelivr.net/npm/simple-icons@v12/icons/ibm.svg',
  microsoft: 'https://cdn.jsdelivr.net/npm/simple-icons@v12/icons/microsoft.svg',
  salesforce: 'https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/salesforce.svg',
  adobe: 'https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/adobe.svg',
  oracle: 'https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/oracle.svg',
  tencentqq: 'https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/tencentqq.svg',
  openai: 'https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/openai.svg',
  bytedance: 'https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/bytedance.svg',
}

export const COMPANY_LOGO_URL = (slug) => LEGACY_ICON_URLS[slug] || `https://cdn.simpleicons.org/${slug}`
